id: green-swordtail
category: fish
type: fish
fish: "Green Swordtail"
related: [fishing-spots/the-wakeful-torana, ksiroda, fishing-spots/pavana-s-remorse, fishing-spots/the-font-of-maya]
tags: [fish, fishing, nature]
status: stable
