id: merlthor-goby
category: fish
type: fish
fish: "Merlthor Goby"
related: [fishing-spots/limsa-lominsa-lower-decks, fishing-spots/limsa-lominsa-upper-decks, zephyr-drift, summerford, moraby-bay, cedarwood, south-bloodshore, skull-valley, isles-of-umbra-northshore, fishing-spots/the-ship-graveyard, cape-westwind, fishing-spots/reaver-hide, rhotano-sea-privateer-sterncastle, north-isle-of-endless-summer]
tags: [fish, fishing, nature]
status: stable
