id: bone-crayfish
category: fish
type: fish
fish: "Bone Crayfish"
related: [fishing-spots/the-mirror, sweetbloom-pier, fishing-spots/sanctum-of-the-twelve, rootslake, fishing-spots/the-tangle, nophica-s-wells, upper-soot-creek, lower-soot-creek, fishing-spots/the-unholy-heir, fishing-spots/bluefog, the-clutch, fishing-spots/blind-iron-mines]
tags: [fish, fishing, nature]
status: stable
