id: fishy-jellyfish
category: fish
type: fish
fish: "Fishy Jellyfish"
related: [central-soda-lime-channel-2, central-soda-lime-channel-3, central-soda-lime-channel-4, central-soda-lime-channel-5]
tags: [fish, fishing, nature]
status: stable
