id: bonytongue
category: fish
type: fish
fish: "Bonytongue"
related: [everschade, goblinblood, urth-s-gift, lake-tahtotl, northeast-bronze-lake, the-burning-wall, singing-shards, the-lavender-beds, northwest-bronze-lake]
tags: [fish, fishing, nature]
status: stable
