id: rothlyt-oyster
category: fish
type: fish
fish: "Rothlyt Oyster"
related: [fishing-spots/moraby-drydocks, fishing-spots/oschon-s-torch, fishing-spots/candlekeep-quay, fishing-spots/swiftperch, skull-valley, fishing-spots/the-brewer-s-beacon, fishing-spots/the-silver-bazaar, fishing-spots/vesper-bay]
tags: [fish, fishing, nature]
status: stable
