id: limne-3-2
category: fishing-spots
type: fishing_spot
fishing_spot: "Limne 3-β"
fish_count: 9
related: [wormhole-worm, unidentified-flying-biomass-ii, triaina, horizon-event, e-b-e-9318, unbegotten, phallaina, e-b-e-852738, sidereal-whale]
tags: [fishing, spot, nature]
status: stable
