id: grinning-anchovy
category: fish
type: fish
fish: "Grinning Anchovy"
related: [kugane-piers, fishing-spots/the-ruby-price, fishing-spots/hells-lid, fishing-spots/the-isle-of-bekko, fishing-spots/shoal-rock, fishing-spots/shirogane]
tags: [fish, fishing, nature]
status: stable
