id: pea-soup
category: food
type: dish
dish: "Pea Soup"
related: [ingredients/dodo-tenderloin, ingredients/jade-peas, ingredients/mineral-water, ingredients/table-salt, ingredients/wild-onion]
tags: [food, cuisine]
status: stable
