id: grade-2-skybuilders-vampiric-tapestry
category: fish
type: fish
fish: "Grade 2 Skybuilders' Vampiric Tapestry"
related: [blustery-cloudtop-2, calm-cloudtop-2, swirling-cloudtop-2, windswept-cloudtop]
tags: [fish, fishing, nature]
status: stable
