id: chives
category: ingredients
type: ingredient
ingredient: "Chives"
related: [food/angler-stew, food/clam-chowder, food/emerald-soup, food/stuffed-chysahl]
tags: [ingredient, food, cooking]
status: stable
