id: the-hermit-s-hovel
category: sightseeing
type: vista
place: "Outer La Noscea"
time: ["18:00", "04:59"]
weather: "Rain"
emote: "/lounge"
related: [rain]
tags: [sightseeing, vista, travel]
status: stable
