id: mudskipper
category: fish
type: fish
fish: "Mudskipper"
related: [hopeseed-pond, the-footfalls, the-unholy-heir, north-drybone, south-drybone, haukke-manor]
tags: [fish, fishing, nature]
status: stable
