id: authentic-starlight-celebration-mmxviii-advertisement
category: furniture
type: furnishing
furnishing: "Authentic Starlight Celebration MMXVIII Advertisement"
tags: [furniture, housing]
status: stable
