id: yak-t-el
category: world
type: zone
rank: landmark
parent: world/yok-tural
zone: "Yak T'el"
region: "Yok Tural"
related: [yok-tural, fair-skies, clear-skies, clouds, fog, rain, world/ankledeep, world/bitterbark-cenote, world/blue-eyes-abode, world/cenote-jayunja, world/cenote-neyozzote, world/choliselvaas, world/dirigible-landing-yak-t-el, world/garden-of-the-stars, world/gok-draak-descent, world/gok-golma, world/golmajiik-grove, world/iq-braax, world/iq-rrax-tsoly, world/mamook, world/moxutural-zooj, world/nightstalker-s-shadow, world/sapsweet-cenote, world/the-fanged-foundry, world/the-glory-of-moxuk-reloonuk, world/the-skydeep-cenote, world/the-ty-iinbek-traverse, world/tree-of-living-light, world/village-of-ilyon-asoh, world/whetstone, world/xd-aa-talat-tsoly, world/xmun-hojaw, world/xobr-it-tsoly, world/xty-iinbek-tsoly, world/yak-awak-tsoly]
tags: [zone, region, travel]
status: stable
