id: eunuch-crayfish
category: fish
type: fish
fish: "Eunuch Crayfish"
related: [the-vein, sweetbloom-pier, springripple-brook, upper-hathoeva-river, lower-hathoeva-river, east-hathoeva-river, fishing-spots/woad-whisper-canyon, fishing-spots/empty-heart, nophica-s-wells, the-footfalls, fishing-spots/the-goblet]
tags: [fish, fishing, nature]
status: stable
