id: eunuch-crayfish
category: fish
type: fish
fish: "Eunuch Crayfish"
related: [the-vein, sweetbloom-pier, springripple-brook, upper-hathoeva-river, lower-hathoeva-river, east-hathoeva-river, woad-whisper-canyon, empty-heart, nophica-s-wells, the-footfalls, the-goblet]
tags: [fish, fishing, nature]
status: stable
