id: lunar-raiamas
category: fish
type: fish
fish: "Lunar Raiamas"
related: [westward-hop-print-2, westward-hop-print-3, westward-hop-print-4, westward-hop-print-6, westward-hop-print-7, westward-hop-print-8]
tags: [fish, fishing, nature]
status: stable
