id: kugane
category: world
type: aetheryte
rank: aetheryte
parent: world/hingashi
aetheryte: "Kugane"
region: "Hingashi"
tags: [aetheryte, travel, teleport]
related: [hingashi, fair-skies, clouds, clear-skies, rain, fog, world/bokairo-inn, world/bokaisen-hot-springs, world/garlean-consulate, world/go-ban-kura, world/kogane-dori-markets, world/kokajiya, world/kugane-ofunakura, world/matsuba-gate, world/matsuba-square, world/pier-1, world/rakusui-gardens, world/rakuza-district, world/san-ban-kura, world/sanjo-hanamachi, world/sekiseigumi-barracks, world/shiokaze-hostelry, world/tasogare-bridge, world/tenkonto, world/thavnairian-consulate, world/the-kuroboro-maru, world/the-mujikoza, world/the-ruby-bazaar, world/the-statue-of-zuiko, world/umineko-teahouse]
status: stable
