id: pipira
category: fish
type: fish
fish: "Pipira"
related: [the-vein, the-mirror, sweetbloom-pier, whispering-gorge, jadeite-flood, lower-black-tea-brook, upper-black-tea-brook, the-lavender-beds]
tags: [fish, fishing, nature]
status: stable
