id: ignus-snail
category: fish
type: fish
fish: "Ignus Snail"
related: [north-silvertear, fishing-spots/rathefrost, the-deep-tangle, fishing-spots/the-burning-wall, fishing-spots/zahar-ak, ceruleum-field, fishing-spots/bluefog, the-north-shards, fishing-spots/parata-s-peace, the-long-climb]
tags: [fish, fishing, nature]
status: stable
