id: highland-cabbage
category: ingredients
type: ingredient
ingredient: "Highland Cabbage"
related: [food/sausage-and-sauerkraut, food/stuffed-highland-cabbage]
tags: [ingredient, food, cooking]
status: stable
