id: melancholia
category: fish
type: fish
fish: "Melancholia"
related: [northward-hop-print-2, northward-hop-print-3, northward-hop-print-4, northward-hop-print-5, northward-hop-print-6, northward-hop-print-7, northward-hop-print-8]
tags: [fish, fishing, nature]
status: stable
