id: gudgeon
category: fish
type: fish
fish: "Gudgeon"
related: [the-vein, the-mirror, west-agelyss-river, nym-river, the-mourning-widow, nophica-s-wells, whispering-gorge, jadeite-flood, lower-black-tea-brook, upper-black-tea-brook]
tags: [fish, fishing, nature]
status: stable
