id: northern-pike
category: fish
type: fish
fish: "Northern Pike"
related: [fishing-spots/the-nail, fishing-spots/the-weeping-saint, exploratory-ice-hole]
tags: [fish, fishing, nature]
status: stable
