id: whilom-catfish
category: fish
type: fish
fish: "Whilom Catfish"
related: [fishing-spots/the-hundred-throes, fishing-spots/whilom-river, the-smoldering-wastes]
tags: [fish, fishing, nature]
status: stable
