id: mudcrab
category: fish
type: fish
fish: "Mudcrab"
related: [hopeseed-pond, lower-hathoeva-river, east-hathoeva-river, goblinblood, lake-tahtotl, the-juggernaut, the-footfalls, the-unholy-heir, north-drybone, south-drybone, zahar-ak, haukke-manor, singing-shards]
tags: [fish, fishing, nature]
status: stable
