id: monke-onke
category: fish
type: fish
fish: "Monke Onke"
related: [everschade, fishing-spots/urth-s-gift, the-deep-tangle, east-agelyss-river, fishing-spots/haukke-manor, fishing-spots/the-lavender-beds]
tags: [fish, fishing, nature]
status: stable
