id: monke-onke
category: fish
type: fish
fish: "Monke Onke"
related: [everschade, urth-s-gift, the-deep-tangle, east-agelyss-river, haukke-manor, the-lavender-beds]
tags: [fish, fishing, nature]
status: stable
