id: crimson-trout
category: fish
type: fish
fish: "Crimson Trout"
related: [coerthas-river, fishing-spots/the-nail, fishing-spots/the-weeping-saint, dragonhead-latrines, fishing-spots/snowcloak]
tags: [fish, fishing, nature]
status: stable
