id: fruit-and-aloe-jelly
category: food
type: dish
dish: "Fruit and Aloe Jelly"
related: [ingredients/branchbearer-fruit, ingredients/gelatin, ingredients/mesquite-beans, ingredients/ovibos-milk, ingredients/royal-maple-syrup, ingredients/turali-aloe]
tags: [food, cuisine]
status: stable
