id: palus-arsenici-9
category: fishing-spots
type: fishing_spot
fishing_spot: "Palus Arsenici"
fish_count: 6
related: [lunar-scorpion, moonwhip, polypus-arsenici, darkside-shrimp, stardust-octopus, raw-moonbright-tourmaline]
tags: [fishing, spot, nature]
status: stable
