id: norvrandt
category: world
type: region
rank: region
related: [lakeland, kholusia, amh-araeng, il-mheg, the-rak-tika-greatwood, the-tempest, the-crystarium, eulmore]
tags: [region, geography]
status: stable
